import { Organization, GapOfferRequest, Commitment, EvidenceLearning } from './types';

export const YORKSHIRE_ORGANIZATIONS: Organization[] = [
  // 1. Home and Community
  {
    id: 'org-yorkshire-sheffield-manor',
    name: 'Sheffield Manor Castle Youth Trust',
    location: 'Sheffield',
    address: 'Manor Park Centre, Sheffield, S2 1FJ',
    keyContact: 'Sarah Jenkins (Youth Work Lead)',
    currentProjectsCount: 3,
    impact: 'Supported 180 disengaged young people into college placements and health sector traineeships in 2025.',
    lookingForDetail: 'Volunteers, mental health mentors, and community funding for weekend drop-ins.',
    latitude: 53.3700,
    longitude: -1.4420,
    assignedTab: 'Home and Community',
    journeyStages: ['Home and Community', 'School'],
    sector: 'Foundational',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Operating a community youth hub providing drop-in career counselling, mental health first aid, and functional literacy support.',
    solutions: [
      'Street-based youth engagement in high-deprivation Sheffield East wards.',
      'Pre-employment confidence building and CV assistance.',
      'Connecting youth directly with Sheffield Teaching Hospitals NHS Trust entry roles.'
    ],
    description: 'A grassroots trust dedicated to raising aspirations and delivering tailored support for young people living in Sheffield East.',
    contactEmail: 'info@manorcastleyouth.org.uk',
    website: 'https://manorcastleyouth.org.uk',
    workingWithOaha: false,
  },
  {
    id: 'org-yorkshire-halifax-community',
    name: 'Calder Valley Youth & Community Collective',
    location: 'Halifax',
    address: 'Square Chapel Arts, Halifax, HX1 1QG',
    keyContact: 'Liam Brook (Community Engagement Officer)',
    currentProjectsCount: 2,
    impact: 'Reached over 140 young residents in upper Calderdale valley towns with youth mentoring.',
    lookingForDetail: 'Refurbished digital devices for family homework sessions.',
    latitude: 53.7230,
    longitude: -1.8600,
    assignedTab: 'Home and Community',
    journeyStages: ['Home and Community'],
    sector: 'Foundational',
    lookingFor: 'Funding',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Delivering mobile youth support and family engagement drop-ins across Todmorden, Hebden Bridge, and Halifax.',
    solutions: [
      'Mobile youth advice pop-ups in rural valley communities.',
      'Peer-to-peer mental health support groups.',
      'Family digital inclusion kits for home study.'
    ],
    description: 'Connecting isolated young people across Calderdale with local mentoring, creative workshops, and community services.',
    contactEmail: 'hello@caldervalleyyouth.org.uk',
    website: 'https://caldervalleyyouth.org.uk',
    workingWithOaha: true,
  },

  // 2. School
  {
    id: 'org-yorkshire-bradford-digital',
    name: 'Bradford Youth Tech & Creative Hub',
    location: 'Bradford',
    address: '24 Sunbridge Road, Bradford, BD1 2AA',
    keyContact: 'Tariq Mahmood (Director of Community Tech)',
    currentProjectsCount: 4,
    impact: 'Upskilled 210 unengaged school-leavers in software engineering and digital media in 2025.',
    lookingForDetail: 'Laptops, industry speakers, and tech internships in West Yorkshire.',
    latitude: 53.7939,
    longitude: -1.7564,
    assignedTab: 'School',
    journeyStages: ['School', 'Entry to Work'],
    sector: 'Tech/Digital',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Running intensive coding clubs and digital creativity workshops in Manningham and Girlington secondary schools.',
    solutions: [
      'Providing free laptop loans and 5G Wi-Fi dongles to trainees.',
      'Partnering with Leeds & Bradford tech firms for guaranteed job interview slots.',
      'Hosting weekend hackathons focused on local community issues.'
    ],
    description: 'Empowering young Bradfordians with modern software engineering skills, breaking down barriers to high-paying digital technology careers.',
    contactEmail: 'contact@bradfordtechhub.org.uk',
    website: 'https://bradfordtechhub.org.uk',
    workingWithOaha: true,
  },
  {
    id: 'org-yorkshire-wakefield-arts',
    name: 'Wakefield Youth Creative & Cultural Pathways',
    location: 'Wakefield',
    address: 'The Hepworth Wakefield, Gallery Walk, Wakefield, WF1 5JI',
    keyContact: 'Emma Richardson (Education Lead)',
    currentProjectsCount: 3,
    impact: 'Engaged 350 pupils from lower-income Wakefield postcodes in creative industries career taster sessions.',
    lookingForDetail: 'Local design and media employers for student mentoring.',
    latitude: 53.6800,
    longitude: -1.4970,
    assignedTab: 'School',
    journeyStages: ['School', 'Post-16 Education and Training'],
    sector: 'Creative',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Connecting local high schools with hands-on gallery design, set building, and digital art apprenticeships.',
    solutions: [
      'Creative industries career insight days in Wakefield secondary schools.',
      'Subsidized transport to cultural arts hubs for school groups.',
      'Portfolio building workshops for Year 11 pupils.'
    ],
    description: 'Unlocking creative potential and career pathways for young people across Wakefield, Castleford, and Pontefract.',
    contactEmail: 'pathways@wakefieldcreative.org.uk',
    website: 'https://wakefieldcreative.org.uk',
    workingWithOaha: false,
  },

  // 3. Post-16 Education and Training
  {
    id: 'org-yorkshire-amrc-tech',
    name: 'South Yorkshire AMRC STEM Academy',
    location: 'Rotherham',
    address: 'Advanced Manufacturing Park, Rotherham, S60 5WG',
    keyContact: 'Dr. Helen Wright (Head of Technical Apprenticeships)',
    currentProjectsCount: 5,
    impact: 'Trained over 320 young engineering recruits with 94% retention across South Yorkshire firms.',
    lookingForDetail: 'SME manufacturing employers seeking co-funded apprentice placements.',
    latitude: 53.3850,
    longitude: -1.3780,
    assignedTab: 'Post-16 Education and Training',
    journeyStages: ['Post-16 Education and Training', 'Entry to Work'],
    sector: 'Tech/Digital',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Partnering with local manufacturing firms to create high-value apprenticeships for disadvantaged youth in Rotherham and Sheffield.',
    solutions: [
      'Creating sponsored apprenticeship pathways for young people in former coalfield wards.',
      'Providing technical mentors from the AMRC research team.',
      'Deploying mobile precision tooling workshops to secondary schools.'
    ],
    description: 'A world-class technical training center connecting young people across South Yorkshire directly into advanced manufacturing, clean tech, and robotics careers.',
    contactEmail: 'apprenticeships@amrc-academy.yorkshire.org.uk',
    website: 'https://amrc-academy.yorkshire.org.uk',
    workingWithOaha: true,
  },
  {
    id: 'org-yorkshire-doncaster-green',
    name: 'Doncaster Clean Energy & Logistics Skills Network',
    location: 'Doncaster',
    address: 'Rail Skills Campus, Doncaster, DN1 2QF',
    keyContact: 'Mark Thompson (Skills Director)',
    currentProjectsCount: 4,
    impact: 'Placed 95 young apprentices in rail engineering and green logistics firms in South Yorkshire.',
    lookingForDetail: 'Transport subsidy funding for shift workers.',
    latitude: 53.5228,
    longitude: -1.1311,
    assignedTab: 'Post-16 Education and Training',
    journeyStages: ['Post-16 Education and Training', 'In Work'],
    sector: 'Green Economy',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Establishing green transport pass schemes for night-shift logistics apprentices operating near Doncaster iPort.',
    solutions: [
      'Negotiating shared employer shuttle buses to logistics hubs.',
      'Delivering safety and low-carbon maintenance certifications.',
      'Mentoring young workers transitioning into team leader positions.'
    ],
    description: 'Transforming Doncaster into a center of excellence for sustainable transport, rail engineering, and green supply chain careers.',
    contactEmail: 'info@doncastergreenskills.co.uk',
    website: 'https://doncastergreenskills.co.uk',
    workingWithOaha: true,
  },

  // 4. Entry to Work
  {
    id: 'org-yorkshire-barnsley-digital',
    name: 'Barnsley Digital Futures & Entry-to-Work Hub',
    location: 'Barnsley',
    address: 'Digital Media Centre, County Way, Barnsley, S70 2JW',
    keyContact: 'Gareth Evans (Innovation Lead)',
    currentProjectsCount: 3,
    impact: 'Helped 125 local school-leavers gain non-graduate entry positions in web design, IT support, and digital marketing.',
    lookingForDetail: 'Local employers offering paid entry-level traineeships.',
    latitude: 53.5520,
    longitude: -1.4790,
    assignedTab: 'Entry to Work',
    journeyStages: ['Entry to Work', 'Post-16 Education and Training'],
    sector: 'Tech/Digital',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Delivering practical 8-week entry-to-work academies in cyber security and IT service desk support for Barnsley youth.',
    solutions: [
      'Work-ready soft skill bootcamps tailored to digital employers.',
      'Guaranteed interview pledge with 15 South Yorkshire IT vendors.',
      'Subsidized initial work travel passes.'
    ],
    description: 'Supporting Barnsley youth into thriving tech careers through rapid skill-building and employer connections.',
    contactEmail: 'info@barnsleydigitalfutures.co.uk',
    website: 'https://barnsleydigitalfutures.co.uk',
    workingWithOaha: true,
  },

  // 5. In Work
  {
    id: 'org-yorkshire-leeds-financial',
    name: 'Leeds FinTech Diversity Alliance',
    location: 'Leeds',
    address: 'Wellington Place, Leeds, LS1 4AP',
    keyContact: 'Claire O’Connor (Inclusion Lead)',
    currentProjectsCount: 4,
    impact: 'Audited 14 major financial services firms, securing 45 paid internships and 30 in-work promotions for working-class youth.',
    lookingForDetail: 'Referrals from local schools in Harehills and Gipton.',
    latitude: 53.7955,
    longitude: -1.5540,
    assignedTab: 'In Work',
    journeyStages: ['Entry to Work', 'In Work'],
    sector: 'Tech/Digital',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Connecting working-class youth in Leeds with non-graduate entry roles and progression pathways in banking and fintech.',
    solutions: [
      'Removing degree requirements for entry-level fintech analyst positions.',
      'Providing 1-on-1 industry mentors for junior hires.',
      'Delivering quarterly retention and wage progression checks.'
    ],
    description: 'A coalition of leading Leeds financial institutions opening pathways for diverse local talent to thrive in the region’s growing fintech economy.',
    contactEmail: 'hello@leedsfintechdiversity.org.uk',
    website: 'https://leedsfintechdiversity.org.uk',
    workingWithOaha: true,
  },
  {
    id: 'org-yorkshire-rotherham-advanced',
    name: 'South Yorkshire Advanced Manufacturing Retention Alliance',
    location: 'Rotherham',
    address: 'Gateway Plaza, Rotherham, S60 1AE',
    keyContact: 'Paul Gallagher (Workforce Progression Director)',
    currentProjectsCount: 3,
    impact: 'Improved 12-month retention rates among young manufacturing recruits across Rotherham by 28%.',
    lookingForDetail: 'Technical peer mentors and shift leadership coaches.',
    latitude: 53.4300,
    longitude: -1.3570,
    assignedTab: 'In Work',
    journeyStages: ['In Work'],
    sector: 'Green Economy',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Supporting early-career engineering technicians with peer mentoring, upskilling modules, and clear promotional milestones.',
    solutions: [
      'Peer-to-peer support circles for young machine operators.',
      'Modular green technology certifications for line workers.',
      'Transparent progression pathways negotiated with employers.'
    ],
    description: 'Helping young engineering and manufacturing staff in South Yorkshire progress into sustainable, higher-wage supervisor roles.',
    contactEmail: 'retention@southyorkshiremanufacturing.org.uk',
    website: 'https://southyorkshiremanufacturing.org.uk',
    workingWithOaha: false,
  },

  // 6. Re-entry
  {
    id: 'org-yorkshire-kirklees-green',
    name: 'Kirklees Retrofit & Green Trades Guild',
    location: 'Huddersfield',
    address: 'St George’s Square, Huddersfield, HD1 1JF',
    keyContact: 'Dave Robinson (Guild Coordinator)',
    currentProjectsCount: 3,
    impact: 'Trained 110 young plumbers and electricians in heat pump installation and solar retrofitting.',
    lookingForDetail: 'Housing associations willing to offer apprenticeship contracts.',
    latitude: 53.6458,
    longitude: -1.7850,
    assignedTab: 'Re-entry',
    journeyStages: ['Re-entry', 'In Work'],
    sector: 'Green Economy',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Partnering with Kirklees Council to deploy young green retrofitting crews across social housing stock.',
    solutions: [
      'Providing subsidized toolkits for young tradespeople.',
      'Delivering heat-pump installation accreditations.',
      'Ensuring fair wage progression for trade apprentices.'
    ],
    description: 'Building a sustainable skilled workforce across Kirklees to deliver warm, energy-efficient homes and green trade careers.',
    contactEmail: 'contact@kirkleesgreentrades.org.uk',
    website: 'https://kirkleesgreentrades.org.uk',
    workingWithOaha: false,
  },
  {
    id: 'org-yorkshire-sheffield-reentry',
    name: 'Sheffield Steel City Second Chance Futures',
    location: 'Sheffield',
    address: 'Victoria Quays, Sheffield, S2 5SY',
    keyContact: 'Marcus Thorne (Re-entry Director)',
    currentProjectsCount: 3,
    impact: 'Successfully placed 85 young adults with justice system contact into stable green transport and fabrication jobs.',
    lookingForDetail: 'Inclusive employers willing to offer second-chance job interviews in Sheffield and Rotherham.',
    latitude: 53.3850,
    longitude: -1.4600,
    assignedTab: 'Re-entry',
    journeyStages: ['Re-entry', 'Entry to Work'],
    sector: 'Green Economy',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Connecting young adult re-entrants with intensive 6-week practical trades training and guaranteed interviews.',
    solutions: [
      'Tailored 1-on-1 reintegration coaching and travel support.',
      'Ban the Box recruitment partnerships with local contractors.',
      'Peer mentorship from successful re-entry alumni.'
    ],
    description: 'Transforming lives across Sheffield through fair-chance employment in high-demand green trades and logistics.',
    contactEmail: 'futures@sheffieldsecondchance.org.uk',
    website: 'https://sheffieldsecondchance.org.uk',
    workingWithOaha: true,
  }
];

export const YORKSHIRE_GAPS_OFFERS: GapOfferRequest[] = [
  // Home and Community
  {
    id: 'gap-yorkshire-hc-1',
    type: 'Gap',
    title: 'Lack of evening community transport for isolated youth in South Yorkshire former mining villages',
    submittedBy: 'Marcus Vance',
    organization: 'Doncaster & Barnsley Youth Action',
    contactEmail: 'marcus@southyorkshireyouth.org.uk',
    content: 'Young people living in Rossington, Goldthorpe, and Grimethorpe cannot access after-school youth hubs or evening skills drop-ins because rural bus services stop at 7:30 PM.',
    assignedTab: 'Home and Community',
    region: 'southeast',
    category: 'resource',
    urgency: 'urgent'
  },
  {
    id: 'offer-yorkshire-hc-1',
    type: 'Offer',
    title: 'Free community mental health first aid training for youth mentors in Sheffield East',
    submittedBy: 'Sarah Jenkins',
    organization: 'Sheffield Manor Castle Youth Trust',
    contactEmail: 'info@manorcastleyouth.org.uk',
    content: 'Offering 30 fully funded training slots for grassroots community leaders and youth workers to become certified Youth Mental Health First Aiders.',
    assignedTab: 'Home and Community',
    region: 'southeast',
    category: 'resource',
    urgency: 'not urgent'
  },
  {
    id: 'request-yorkshire-hc-1',
    type: 'Request',
    title: 'Seeking 15 refurbished laptops for family homework stations in Halifax',
    submittedBy: 'Liam Brook',
    organization: 'Calder Valley Youth Collective',
    contactEmail: 'hello@caldervalleyyouth.org.uk',
    content: 'We need 15 refurbished laptops and Wi-Fi dongles to equip our drop-in youth center in Halifax for school pupils without home internet access.',
    assignedTab: 'Home and Community',
    region: 'north',
    category: 'resource',
    urgency: 'urgent'
  },

  // School
  {
    id: 'gap-yorkshire-sch-1',
    type: 'Gap',
    title: 'Digital equipment deficit in Manningham youth center & secondary schools',
    submittedBy: 'Amina Begum',
    organization: 'Manningham Community Forum',
    contactEmail: 'amina@manninghamforum.org.uk',
    content: 'Over 60 school-leavers attending our after-school tech club in Bradford share only 4 outdated laptops. We urgently need 20 refurbished devices for coding classes.',
    assignedTab: 'School',
    region: 'north',
    category: 'resource',
    urgency: 'urgent'
  },
  {
    id: 'offer-yorkshire-sch-1',
    type: 'Offer',
    title: 'Free AMRC precision tooling and robotics workshops for Rotherham school groups',
    submittedBy: 'Dr. Helen Wright',
    organization: 'South Yorkshire AMRC STEM Academy',
    contactEmail: 'apprenticeships@amrc-academy.yorkshire.org.uk',
    content: 'Offering 15 fully funded 1-day robotics and precision engineering taster sessions for Year 10 and Year 11 classes across Rotherham and Sheffield.',
    assignedTab: 'School',
    region: 'southeast',
    category: 'job',
    urgency: 'not urgent'
  },
  {
    id: 'request-yorkshire-sch-1',
    type: 'Request',
    title: 'Seeking local STEM speakers for Year 10 careers week in Doncaster secondary schools',
    submittedBy: 'Mark Thompson',
    organization: 'Doncaster Clean Energy Network',
    contactEmail: 'info@doncastergreenskills.co.uk',
    content: 'Looking for 10 green engineering and logistics ambassadors to deliver 45-minute interactive talks in 5 Doncaster secondary schools during National Careers Week.',
    assignedTab: 'School',
    region: 'southeast',
    category: 'resource',
    urgency: 'not urgent'
  },

  // Post-16 Education and Training
  {
    id: 'gap-yorkshire-p16-1',
    type: 'Gap',
    title: 'Travel cost barriers for college trainees commuting between Huddersfield and Dewsbury',
    submittedBy: 'Dave Robinson',
    organization: 'Kirklees Skills Alliance',
    contactEmail: 'contact@kirkleesgreentrades.org.uk',
    content: 'Young post-16 vocational students face up to £45 per week in bus fares to attend practical trade workshops, causing higher dropout rates.',
    assignedTab: 'Post-16 Education and Training',
    region: 'north',
    category: 'funding',
    urgency: 'urgent'
  },
  {
    id: 'offer-yorkshire-p16-1',
    type: 'Offer',
    title: '25 Paid 6-week summer tech internships in Leeds city center',
    submittedBy: 'Claire O’Connor',
    organization: 'Leeds FinTech Diversity Alliance',
    contactEmail: 'hello@leedsfintechdiversity.org.uk',
    content: 'Offering paid 6-week software development and business analytics internships for young people aged 18-24 living in low-income Leeds postcodes.',
    assignedTab: 'Post-16 Education and Training',
    region: 'north',
    category: 'job',
    urgency: 'not urgent'
  },
  {
    id: 'request-yorkshire-p16-1',
    type: 'Request',
    title: 'Seeking co-funded manufacturing apprentice slots across South Yorkshire suppliers',
    submittedBy: 'Dr. Helen Wright',
    organization: 'AMRC STEM Academy',
    contactEmail: 'apprenticeships@amrc-academy.yorkshire.org.uk',
    content: 'Seeking 12 advanced manufacturing SMEs in Rotherham, Sheffield, and Barnsley willing to offer 50% co-funded Level 3 engineering apprenticeships.',
    assignedTab: 'Post-16 Education and Training',
    region: 'southeast',
    category: 'job',
    urgency: 'urgent'
  },

  // Entry to Work
  {
    id: 'gap-yorkshire-etw-1',
    type: 'Gap',
    title: 'Lack of shift transport to Doncaster iPort logistics hub for young night workers',
    submittedBy: 'Marcus Vance',
    organization: 'Doncaster Youth Action',
    contactEmail: 'marcus@doncasteryouth.org.uk',
    content: 'Young logistics apprentices in Mexborough and Rossington cannot take up night-shift roles because local buses stop running at 9 PM.',
    assignedTab: 'Entry to Work',
    region: 'southeast',
    category: 'resource',
    urgency: 'urgent'
  },
  {
    id: 'offer-yorkshire-etw-1',
    type: 'Offer',
    title: 'Guaranteed interview pledge for Barnsley digital bootcamp graduates',
    submittedBy: 'Gareth Evans',
    organization: 'Barnsley Digital Futures Hub',
    contactEmail: 'info@barnsleydigitalfutures.co.uk',
    content: 'Offering guaranteed interviews for 30 young Barnsley bootcamps graduates across 10 partner IT service companies in West and South Yorkshire.',
    assignedTab: 'Entry to Work',
    region: 'north',
    category: 'job',
    urgency: 'not urgent'
  },

  // In Work
  {
    id: 'gap-yorkshire-iw-1',
    type: 'Gap',
    title: 'High early attrition among young apprentice technicians in Rotherham plants',
    submittedBy: 'Paul Gallagher',
    organization: 'South Yorkshire Manufacturing Alliance',
    contactEmail: 'retention@southyorkshiremanufacturing.org.uk',
    content: 'Over 35% of 18-21 year old line recruits leave within 9 months due to lack of shift peer support and isolated workplace environments.',
    assignedTab: 'In Work',
    region: 'southeast',
    category: 'others',
    urgency: 'urgent'
  },
  {
    id: 'offer-yorkshire-iw-1',
    type: 'Offer',
    title: '1-on-1 career progression mentorship for working-class staff in Leeds finance',
    submittedBy: 'Claire O’Connor',
    organization: 'Leeds FinTech Diversity Alliance',
    contactEmail: 'hello@leedsfintechdiversity.org.uk',
    content: 'Providing 40 senior finance and tech mentors to support junior non-graduate employees in Leeds financial firms over a 12-month career progression cycle.',
    assignedTab: 'In Work',
    region: 'north',
    category: 'job',
    urgency: 'not urgent'
  },

  // Re-entry
  {
    id: 'gap-yorkshire-re-1',
    type: 'Gap',
    title: 'Shortage of inclusive second-chance employers for young adult re-entrants in Sheffield',
    submittedBy: 'Marcus Thorne',
    organization: 'Sheffield Steel City Second Chance Futures',
    contactEmail: 'futures@sheffieldsecondchance.org.uk',
    content: 'Young adults exiting justice contact face immediate application rejections due to blanket disclosure policies in manufacturing and warehousing.',
    assignedTab: 'Re-entry',
    region: 'southeast',
    category: 'job',
    urgency: 'urgent'
  },
  {
    id: 'request-yorkshire-re-1',
    type: 'Request',
    title: 'Seeking local green building employers for Huddersfield apprentice placements',
    submittedBy: 'Dave Robinson',
    organization: 'Kirklees Retrofit Guild',
    contactEmail: 'contact@kirkleesgreentrades.org.uk',
    content: 'We have 12 certified heat-pump trainees ready for workplace placements. We need accredited building contractors in Kirklees and Calderdale to take them on.',
    assignedTab: 'Re-entry',
    region: 'north',
    category: 'job',
    urgency: 'urgent'
  }
];

export const YORKSHIRE_COMMITMENTS: Commitment[] = [
  {
    id: 'commit-yorkshire-hc-1',
    title: 'Sheffield East Community Youth Wellbeing Accord',
    partnerName: 'Sheffield City Council & Manor Castle Youth Trust',
    owner: 'Sarah Jenkins & Cllr Tom Hunt',
    timescale: 'Q4 2026',
    progress: 'Active Pilot',
    nextSteps: 'Establishing 3 evening youth drop-in centers in Manor Park and Wybourn with NHS mental health support.',
    dependencies: 'Local authority public health grant sign-off.',
    assignedTab: 'Home and Community',
    region: 'southeast'
  },
  {
    id: 'commit-yorkshire-sch-1',
    title: 'Bradford Tech & Digital Inclusion Charter',
    partnerName: 'Bradford Metropolitan District Council & Tech Nation',
    owner: 'Tariq Mahmood & Kersten England',
    timescale: 'Q3 2026',
    progress: 'Drafting',
    nextSteps: 'Securing 20 corporate pledges for laptop donations and guaranteed job interviews for bootcamp graduates.',
    dependencies: 'Broadband infrastructure sign-off in Manningham.',
    assignedTab: 'School',
    region: 'north'
  },
  {
    id: 'commit-yorkshire-p16-1',
    title: 'Doncaster iPort Shift Workers Transport Pass',
    partnerName: 'Doncaster Council & First Bus South Yorkshire',
    owner: 'Mark Thompson & Doncaster Logistics Forum',
    timescale: 'Q1 2027',
    progress: 'Active Pilot',
    nextSteps: 'Testing dedicated 10 PM and 5 AM shuttle bus loops for young logistics apprentices.',
    dependencies: 'Employer transport subsidy commitments.',
    assignedTab: 'Post-16 Education and Training',
    region: 'southeast'
  },
  {
    id: 'commit-yorkshire-etw-1',
    title: 'West Yorkshire Non-Degree Digital Fast-Track',
    partnerName: 'West Yorkshire Combined Authority (WYCA) & Leeds Digital Guild',
    owner: 'Gareth Evans & Mayor Tracy Brabin',
    timescale: 'Q3 2026',
    progress: 'Active Pilot',
    nextSteps: 'Enrolling 60 non-graduate young jobseekers across Bradford, Leeds, and Wakefield into fast-track entry roles.',
    dependencies: 'Employer skills charter adoption.',
    assignedTab: 'Entry to Work',
    region: 'north'
  },
  {
    id: 'commit-yorkshire-iw-1',
    title: 'South Yorkshire Advanced Manufacturing In-Work Progression Charter',
    partnerName: 'South Yorkshire Mayoral Combined Authority (SYMCA) & AMRC',
    owner: 'Oliver Coppard (Mayor) & Dr. Helen Wright',
    timescale: 'Q2 2027',
    progress: 'Drafting',
    nextSteps: 'Piloting wage progression benchmarks across 15 engineering employers in Rotherham and Sheffield.',
    dependencies: 'Regional skills levy matching fund.',
    assignedTab: 'In Work',
    region: 'southeast'
  },
  {
    id: 'commit-yorkshire-re-1',
    title: 'Kirklees & Sheffield Green Retrofit Youth Re-entry Guarantee',
    partnerName: 'Kirklees Council, Sheffield City Council & Housing Associations',
    owner: 'Dave Robinson & Marcus Thorne',
    timescale: 'Q4 2026',
    progress: 'Active Pilot',
    nextSteps: 'Deploying initial 35 green energy apprentice placements across social housing retrofit schemes.',
    dependencies: 'Co-funding approval from regional retrofit budget.',
    assignedTab: 'Re-entry',
    region: 'north'
  }
];

export const YORKSHIRE_EVIDENCE_LEARNING: EvidenceLearning[] = [
  {
    id: 'evidence-yorkshire-hc-1',
    title: 'Community Digital Hub Outreach in Manningham, Bradford',
    logType: 'Community Feedback',
    assignedTab: 'Home and Community',
    description: 'Youth feedback highlighted that formal college environments intimidated unengaged 16-18 year olds.',
    whatChanged: 'Moved introductory coding sessions into trusted local community halls, increasing attendance by 65%.',
    region: 'north'
  },
  {
    id: 'evidence-yorkshire-sch-1',
    title: 'Impact of AMRC Mobile Engineering Workshops in Rotherham Schools',
    logType: 'Outcome Metric',
    assignedTab: 'School',
    description: 'Brought mobile 3D printing and precision tooling rigs to 12 secondary schools in former coalfield wards.',
    whatChanged: 'Increased student applications for Level 3 engineering apprenticeships by 42% year-on-year.',
    region: 'southeast'
  },
  {
    id: 'evidence-yorkshire-p16-1',
    title: 'Addressing Travel Costs for Vocational College Students in Kirklees',
    logType: 'Barrier Encountered',
    assignedTab: 'Post-16 Education and Training',
    description: 'Data showed a 28% drop-out rate among Dewsbury students commuting to Huddersfield technical workshops due to bus fares.',
    whatChanged: 'Introduced a subsidized college bus pass, restoring attendance rates to 94%.',
    region: 'north'
  },
  {
    id: 'evidence-yorkshire-etw-1',
    title: 'Impact of Dedicated Shift Transport on Youth Logistics Retention in Doncaster',
    logType: 'Outcome Metric',
    assignedTab: 'Entry to Work',
    description: 'Surveying 45 young night-shift logistics workers showed that transport uncertainty was the #1 cause of 90-day dropouts.',
    whatChanged: 'First Bus piloted a subsidized 10 PM shuttle route, reducing 90-day apprentice attrition by 38% in the first quarter.',
    region: 'southeast'
  },
  {
    id: 'evidence-yorkshire-iw-1',
    title: 'Removing Degree Requirements for Junior Tech Roles in Leeds',
    logType: 'Delivery Learning',
    assignedTab: 'In Work',
    description: 'Collaborating with 8 financial firms to replace computer science degree requirements with practical skill tests.',
    whatChanged: 'Applicant diversity increased by 210%, with 82% of non-graduate recruits passing 6-month probation with high performance ratings.',
    region: 'north'
  },
  {
    id: 'evidence-yorkshire-re-1',
    title: 'Second-Chance Recruitment in Green Construction across South & West Yorkshire',
    logType: 'Key Decision',
    assignedTab: 'Re-entry',
    description: 'Partnered with social housing retrofit contractors to remove criminal conviction checkboxes on initial application forms.',
    whatChanged: 'Placed 42 young adult re-entrants into steady employment with 0 re-offending recorded over 12 months.',
    region: 'north'
  }
];
