import { Organization, TabInfo } from './types';

export const SYSTEMIC_TABS: TabInfo[] = [
  {
    id: 'Visibility',
    label: 'Visibility',
    subLabel: 'Early mapping & outreach',
    description: 'Pathways may exist, but they are not always visible, relatable or easy to understand early enough.',
    colorClass: 'border-amber-500 text-amber-400 bg-amber-950/20',
    badgeColor: 'bg-amber-400/10 text-amber-400 border-amber-400/20'
  },
  {
    id: 'Family Awareness',
    label: 'Family Awareness',
    subLabel: 'Engaging parents & carers',
    description: 'Parents, carers and trusted adults shape choices, but routes into local jobs and future sectors are not always clear, current or easy to explain.',
    colorClass: 'border-emerald-500 text-emerald-400 bg-emerald-950/20',
    badgeColor: 'bg-emerald-400/10 text-emerald-400 border-emerald-400/20'
  },
  {
    id: 'Transitions',
    label: 'Transitions',
    subLabel: 'Aligning curriculum with real jobs',
    description: 'Real jobs, future skills and employer demand do not always translate into learner awareness, curriculum links or pathway design.',
    colorClass: 'border-cyan-500 text-cyan-400 bg-cyan-950/20',
    badgeColor: 'bg-cyan-400/10 text-cyan-400 border-cyan-400/20'
  },
  {
    id: 'Navigation',
    label: 'Navigation',
    subLabel: 'Guiding non-linear pathways',
    description: 'Non-linear routes can involve repeated retelling, weak advocacy and complex thresholds.',
    colorClass: 'border-violet-500 text-violet-400 bg-violet-950/20',
    badgeColor: 'bg-violet-400/10 text-violet-400 border-violet-400/20'
  },
  {
    id: 'Translation',
    label: 'Translation',
    subLabel: 'Matching demand to awareness',
    description: 'Real jobs and employer demand do not always translate into learner awareness or pathway design.',
    colorClass: 'border-rose-500 text-rose-400 bg-rose-950/20',
    badgeColor: 'bg-rose-400/10 text-rose-400 border-rose-400/20'
  },
  {
    id: 'Progression',
    label: 'Progression',
    subLabel: 'Tackling workplace culture',
    description: 'Access alone is not progression if cultures still reward familiarity and narrow ideas of “fit”.',
    colorClass: 'border-red-500 text-red-400 bg-red-950/20',
    badgeColor: 'bg-red-400/10 text-red-400 border-red-400/20'
  }
];

export const WELSH_ORGANIZATIONS: Organization[] = [
  // ==================== STAGE 1: VISIBILITY (8 organizations) ====================
  {
    id: 'org-cyo-visibility',
    name: 'Cymru Youth Outreach (CYO)',
    location: 'Valleys (Merthyr Tydfil)',
    address: '12 High Street, Merthyr Tydfil, CF47 8DP',
    keyContact: 'Gareth Jenkins (Director of Engagement)',
    currentProjectsCount: 4,
    impact: 'Connected over 450 disengaged school leavers to local apprenticeship pathways in the last 18 months.',
    lookingForDetail: 'Practical workshops and vehicle space hire in remote villages.',
    latitude: 51.7471,
    longitude: -3.3786,
    assignedTab: 'Visibility',
    sector: 'Foundational',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Deploying custom mobile outreach vans carrying tech & career advisors straight into former coalfield communities.',
    solutions: [
      'Mapping cold spots where youth hubs do not exist to focus pop-up presence.',
      'Providing street-based youth workers with digital toolkits to register unengaged NEET youths.',
      'Running community-hall career discovery events in partnership with local micro-businesses.'
    ],
    description: 'CYO is dedicated to reaching young people aged 16-24 who have disengaged from formal education and statutory job centres in the South Wales Valleys.',
    contactEmail: 'contact@cyo.wales',
    website: 'https://cyo.wales',
    workingWithOaha: true
  },
  {
    id: 'org-bangor-discover-visibility',
    name: 'Bangor Reach & Discover',
    location: 'Bangor',
    address: 'Deiniol Road, Bangor, LL57 2UP',
    keyContact: 'Elen Vaughan (Lead Storyteller)',
    currentProjectsCount: 3,
    impact: 'Designed and distributed 12 bilingual career podcasts with over 5,000 local youth downloads.',
    lookingForDetail: 'Employer partners willing to host creative media trainees.',
    latitude: 53.2274,
    longitude: -4.1293,
    assignedTab: 'Visibility',
    sector: 'Creative',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Producing Welsh-language youth culture podcasts and TikTok mapping campaigns highlighting hidden local apprenticeships.',
    solutions: [
      'Utilising peer-to-peer storytelling to demystify entry-level creative fields.',
      'Bilingual community mapping that details transport routes from Anglesey to North Wales hubs.',
      'Active visual campaigns on social platforms designed by local youths.'
    ],
    description: 'An interactive bilingual creative collective mapping North Wales employment pathways using grassroots digital storytelling.',
    contactEmail: 'post@discoverbangor.cymru',
    website: 'https://discoverbangor.cymru',
    workingWithOaha: false
  },
  {
    id: 'org-clwyd-innovators-visibility',
    name: 'Clwyd Youth Innovators',
    location: 'Wrexham',
    address: 'Regent Street, Wrexham, LL11 1RE',
    keyContact: 'Marc Davies (Digital Inclusion Officer)',
    currentProjectsCount: 5,
    impact: 'Over 120 refurbished laptops delivered to low-income homes with digital skills certificates.',
    lookingForDetail: 'Funding for a new batch of 50 refurbished laptops and volunteer tutors.',
    latitude: 53.0480,
    longitude: -2.9950,
    assignedTab: 'Visibility',
    sector: 'Tech/Digital',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Grassroots coding clubs targeting young people living in social housing estates across North-East Wales.',
    solutions: [
      'Distributing free refurbished laptops paired with local business mentoring.',
      'Delivering micro-credentials in data literacy directly within community sports centres.',
      'Partnering with housing associations to identify and contact inactive young residents.'
    ],
    description: 'A social enterprise breaking down geographic barriers to entry-level software and technical roles in Wrexham and Flintshire.',
    contactEmail: 'info@clwydinnovators.org.uk',
    website: 'https://clwydinnovators.org.uk',
    workingWithOaha: true
  },
  {
    id: 'org-west-coast-tech-visibility',
    name: 'West Wales Coastal Tech Hub',
    location: 'Aberystwyth',
    address: 'Marine Terrace, Aberystwyth, SY23 2AZ',
    keyContact: 'Sian Owen (Community Coordinator)',
    currentProjectsCount: 3,
    impact: 'Hosted 8 pop-up coding camps in rural Ceredigion, reaching 150+ isolated young residents.',
    lookingForDetail: 'Software company partners for rural virtual placements.',
    latitude: 52.4140,
    longitude: -4.0850,
    assignedTab: 'Visibility',
    sector: 'Tech/Digital',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Active Cohorts Open',
    currentProject: 'Delivering mobile digital skills camps across coastal communities and farming heartlands.',
    solutions: [
      'Deploying temporary solar-powered satellite internet links in connectivity cold-spots.',
      'Organising weekend tech taster days for isolated rural school-leavers.',
      'Connecting learners with Welsh remote software companies for micro-shadowing.'
    ],
    description: 'Bringing modern software development, web creation, and tech-sector exposure to geographically isolated rural youth in West Wales.',
    contactEmail: 'sian@westcoastaltech.cymru',
    website: 'https://westcoastaltech.cymru',
    workingWithOaha: false
  },
  {
    id: 'org-gwent-grassroots-visibility',
    name: 'Gwent Grassroots Agency',
    location: 'Newport',
    address: 'Commercial Street, Newport, NP20 1LQ',
    keyContact: 'Liam Murphy (Outreach Coordinator)',
    currentProjectsCount: 4,
    impact: 'Mapped 35 local hidden employers and introduced them to 200 high school students.',
    lookingForDetail: 'Referrals from youth justice and housing support groups.',
    latitude: 51.5905,
    longitude: -3.0030,
    assignedTab: 'Visibility',
    sector: 'Foundational',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Engaging inactive young people at physical hubs, sports facilities, and local skate parks.',
    solutions: [
      'Placing youth workers in leisure centres to offer informal career drop-ins.',
      'Running local sports tournaments paired with informal trade-taster exhibitions.',
      'Offering transport vouchers for youths attending remote job interviews.'
    ],
    description: 'Meeting young people where they gather, offering low-barrier pathways back into training and career opportunities.',
    contactEmail: 'liam@gwentgrassroots.org',
    website: 'https://gwentgrassroots.org',
    workingWithOaha: false
  },
  {
    id: 'org-green-valley-visibility',
    name: 'Green Valley Eco-Builders',
    location: 'Valleys (Aberdare)',
    address: 'Wind Street, Aberdare, CF44 7LL',
    keyContact: 'Owen Thomas (Director)',
    currentProjectsCount: 3,
    impact: 'Exposed 90+ school leavers to modern solar and sustainable building techniques.',
    lookingForDetail: 'Funding for educational simulation tools and eco-construction trial units.',
    latitude: 51.7200,
    longitude: -3.4200,
    assignedTab: 'Visibility',
    sector: 'Green Economy',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Creating interactive mobile workshops mapping out eco-friendly insulation and green retrofitting career steps.',
    solutions: [
      'Designing bilingual visual materials detailing the transition from gas-fitting to low-carbon heat pumps.',
      'Placing demonstration rigs in local agricultural shows to capture rural interest.',
      'Collaborating with schools to map out green construction standards.'
    ],
    description: 'An innovative coalition of eco-contractors working to raise early awareness of circular building and carbon-neutral careers.',
    contactEmail: 'owen@greenvalleybuilders.wales',
    website: 'https://greenvalleybuilders.wales',
    workingWithOaha: true
  },
  {
    id: 'org-cardiff-pixel-visibility',
    name: 'Cardiff Pixel Studio',
    location: 'Cardiff',
    address: 'Trade Street, Cardiff, CF10 5DQ',
    keyContact: 'Sian Roberts (Media Lead)',
    currentProjectsCount: 5,
    impact: 'Organized career discovery games reaching 1,200 children across Cardiff Bay schools.',
    lookingForDetail: 'Employer partners to co-develop interactive gaming curriculum templates.',
    latitude: 51.4800,
    longitude: -3.1800,
    assignedTab: 'Visibility',
    sector: 'Creative',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Leveraging gaming design showcases and live creative streams to make high-value digital careers visible.',
    solutions: [
      'Running interactive Roblox and Minecraft maps of Wales showcasing future energy and media networks.',
      'Collaborating with youth mentors to stream software development in a highly relatable way.',
      'Hosting live design battles in local high schools.'
    ],
    description: 'A forward-thinking creative agency dismantling elite barriers to gaming, graphics, and design pipelines for under-represented youth.',
    contactEmail: 'sian@cardiffpixel.co.uk',
    website: 'https://cardiffpixel.co.uk',
    workingWithOaha: true
  },
  {
    id: 'org-rural-link-visibility',
    name: 'Rural Wales Link',
    location: 'Valleys (Pontypridd)',
    address: 'Llanover Road, Pontypridd, CF37 4HA',
    keyContact: 'Sioned Williams (Outreach Organiser)',
    currentProjectsCount: 2,
    impact: 'Helped 110 isolated farming and valley youths connect to regional technology guilds.',
    lookingForDetail: 'Direct referrals from community support groups in deep rural areas.',
    latitude: 52.3000,
    longitude: -3.6000,
    assignedTab: 'Visibility',
    sector: 'Green Economy',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Promoting carbon-farming, ecological tourism, and remote digital work pathways in deep rural valley villages.',
    solutions: [
      'Setting up rural solar-powered satellite booths showing real-time regional apprenticeships.',
      'Working with family farming groups to map pathways out of seasonal unemployment.',
      'Providing travel and connectivity support to ensure remote candidates are visible.'
    ],
    description: 'A community cooperative raising the visibility of low-carbon land management, tech, and ecological trades in rural communities.',
    contactEmail: 'sioned@ruralwaleslink.org',
    website: 'https://ruralwaleslink.org',
    workingWithOaha: false
  },

  // ==================== STAGE 2: FAMILY AWARENESS (8 organizations) ====================
  {
    id: 'org-family-futures-family',
    name: 'Valleys Family Futures',
    location: 'Valleys (Rhondda)',
    address: 'Pontypridd Road, Porth, CF39 9PG',
    keyContact: 'Sarah Hughes (Family Liaison Manager)',
    currentProjectsCount: 3,
    impact: 'Run 25 "Kitchen Table Chats" dinners, shifting the career perceptions of 180+ local parents.',
    lookingForDetail: 'Referrals of parents whose children are looking at vocational routes.',
    latitude: 51.6153,
    longitude: -3.4282,
    assignedTab: 'Family Awareness',
    sector: 'Foundational',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Hosting "Kitchen Table Chats" where parents meet apprentices and employers to address deep-seated myths around manual and tech sectors.',
    solutions: [
      'Creating bite-sized guides for parents on modern career paths, wage progression, and travel support.',
      'Running family-focused workshop dinners to alleviate concerns about non-university routes.',
      'Offering a bilingual parent advice line translating vocational jargon into understandable terms.'
    ],
    description: 'A community-first trust focusing on shifting multi-generational career perceptions by equipping carers with contemporary knowledge.',
    contactEmail: 'rhondda@familyfutures.wales',
    website: 'https://familyfutures.wales',
    workingWithOaha: true
  },
  {
    id: 'org-parent-connect-family',
    name: 'Cardiff Parent Career Guild',
    location: 'Cardiff',
    address: 'Fitzalan Place, Cardiff, CF24 0EL',
    keyContact: 'Robert Lloyd (Project Director)',
    currentProjectsCount: 4,
    impact: 'Co-designed digital toolkits with 15 parent-teacher associations across Cardiff.',
    lookingForDetail: 'Industry leaders to join parent webinars on emerging local sectors.',
    latitude: 51.4816,
    longitude: -3.1791,
    assignedTab: 'Family Awareness',
    sector: 'Creative',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Co-designing digital career toolkits directly with parent-teacher associations across Cardiff and Newport schools.',
    solutions: [
      'Developing parent-to-parent advocacy networks promoting creative tech opportunities.',
      'Publishing transparency reports explaining starting salaries in modern green and digital sectors.',
      'Providing direct support for parents navigating their children\'s college applications.'
    ],
    description: 'A collaborative network of educators, career advisers, and families establishing collaborative guidance for modern employment paths.',
    contactEmail: 'guild@cardiffparents.org',
    website: 'https://cardiffparents.org',
    workingWithOaha: false
  },
  {
    id: 'org-north-family-family',
    name: 'North Wales Family Advice Hub',
    location: 'Bangor',
    address: 'Holyhead Road, Bangor, LL57 2EE',
    keyContact: 'Nia Roberts (Bilingual Advisor)',
    currentProjectsCount: 2,
    impact: 'Answered over 800 enquiries from parent lines, translating complex jargon into clear guides.',
    lookingForDetail: 'Additional funding to support weekend helpline operations.',
    latitude: 53.2205,
    longitude: -4.1350,
    assignedTab: 'Family Awareness',
    sector: 'Foundational',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Providing multi-lingual helpline and video walkthroughs answering parents\' worries about modern vocational routes.',
    solutions: [
      'Publishing short bilingual explainer videos featuring current young apprentices.',
      'Running virtual drop-ins for rural parents on local public transport subsidies.',
      'Distributing physical printed pathway booklets in local Welsh community halls.'
    ],
    description: 'Supporting North Wales families to guide their children safely through modern non-traditional career landscapes.',
    contactEmail: 'post@northfamilyhub.cymru',
    website: 'https://northfamilyhub.cymru',
    workingWithOaha: false
  },
  {
    id: 'org-wrexham-carers-family',
    name: 'Wrexham Careers & Carers Network',
    location: 'Wrexham',
    address: 'Mold Road, Wrexham, LL11 2AW',
    keyContact: 'David Evans (Network Lead)',
    currentProjectsCount: 3,
    impact: 'Supported 90 parents of neurodivergent children in navigating apprenticeship access schemes.',
    lookingForDetail: 'Employer partners ready to offer supported internships.',
    latitude: 53.0510,
    longitude: -3.0010,
    assignedTab: 'Family Awareness',
    sector: 'Tech/Digital',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Active Cohorts Open',
    currentProject: 'Delivering specialised training sessions for parents of neurodivergent and disabled school-leavers.',
    solutions: [
      'Clarifying employer adjustments and legal rights for young disabled trainees.',
      'Connecting families directly with supportive HR managers in regional tech firms.',
      'Fostering peer-to-peer family support boards to share integration stories.'
    ],
    description: 'Empowering parents of children with additional needs to confidently back vocational apprenticeships and digital pathways.',
    contactEmail: 'david@wrexhamcarers.org',
    website: 'https://wrexhamcarers.org',
    workingWithOaha: false
  },
  {
    id: 'org-west-parents-family',
    name: 'West Wales Parents Link',
    location: 'Llanelli',
    address: 'Stepney Street, Llanelli, SA15 1YN',
    keyContact: 'Catrin Jones (Community Host)',
    currentProjectsCount: 3,
    impact: 'Organised 10 local factory tours for parents to experience modern clean manufacturing environments.',
    lookingForDetail: 'Manufacturing partners willing to open up workshops for family tours.',
    latitude: 51.6812,
    longitude: -4.1610,
    assignedTab: 'Family Awareness',
    sector: 'Green Economy',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Showcasing modern green engineering, wind power and advanced manufacturing facilities directly to parents.',
    solutions: [
      'Dismantling outdated "dirty grease factory" assumptions via clean-tech site visits.',
      'Hosting Q&A lunches connecting parents with green engineering business owners.',
      'Providing realistic salary expectation sheets and pension scheme breakdowns for modern trades.'
    ],
    description: 'Connecting Carmarthenshire parents to the reality of high-skill, low-carbon industrial careers waiting locally.',
    contactEmail: 'catrin@westparentslink.cymru',
    website: 'https://westparentslink.cymru',
    workingWithOaha: true
  },
  {
    id: 'org-gwent-family-family',
    name: 'Gwent Family Network',
    location: 'Newport',
    address: 'Malpas Road, Newport, NP20 5PL',
    keyContact: 'Arwyn Lloyd (Parent Coach)',
    currentProjectsCount: 3,
    impact: 'Established a parent career buddy scheme across Newport reaching 240+ households.',
    lookingForDetail: 'Direct referrals from local primary and secondary school parent councils.',
    latitude: 51.5910,
    longitude: -3.0040,
    assignedTab: 'Family Awareness',
    sector: 'Tech/Digital',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Creating parent-led WhatsApp support forums in both Welsh and English to discuss local software apprenticeships.',
    solutions: [
      'Answering parent concerns regarding immediate wages versus university debt.',
      'Demystifying digital tech work environments for manual trade households.',
      'Providing weekend advice sessions on applying for tech training.'
    ],
    description: 'A community advocacy group helping traditional Newport families understand and support digital and software transitions.',
    contactEmail: 'arwyn@gwentfamily.org',
    website: 'https://gwentfamily.org',
    workingWithOaha: true
  },
  {
    id: 'org-swansea-future-parents',
    name: 'Swansea Future Families',
    location: 'Swansea',
    address: 'Oystermouth Road, Swansea, SA1 3UT',
    keyContact: 'Laura Morris (Program Director)',
    currentProjectsCount: 4,
    impact: 'Guided 130 parents of high schoolers through green energy workshops.',
    lookingForDetail: 'Sponsorship funding to support family exhibition materials and transport.',
    latitude: 51.6210,
    longitude: -3.9450,
    assignedTab: 'Family Awareness',
    sector: 'Green Economy',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Running interactive weekend green-tech family days where parents and children test clean energy equipment together.',
    solutions: [
      'Securing corporate sponsors to subsidise green engineering field trips for parents.',
      'Publishing a physical parent handbook explaining local offshore wind career pipelines.',
      'Providing direct mentoring for parents who wish to retrain into green economy roles themselves.'
    ],
    description: 'Connecting Swansea families to high-growth coastal renewables, carbon logistics, and circular engineering routes.',
    contactEmail: 'laura@swanseafuturefamilies.co.uk',
    website: 'https://swanseafuturefamilies.co.uk',
    workingWithOaha: false
  },
  {
    id: 'org-creative-carers-family',
    name: 'Creative Carers Alliance',
    location: 'Wrexham',
    address: 'Queen Street, Wrexham, LL11 1AP',
    keyContact: 'Dylan Jenkins (Director)',
    currentProjectsCount: 2,
    impact: 'Dispelled myths of unstable freelance work for 150+ creative guardians.',
    lookingForDetail: 'Referrals from school career counsellors and family services.',
    latitude: 51.7450,
    longitude: -3.3750,
    assignedTab: 'Family Awareness',
    sector: 'Creative',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Empowering parents of artistic and creative children to support careers in animation, streaming, and visual production.',
    solutions: [
      'Publishing factual breakdowns on the scale of Wales\' booming television and media market.',
      'Running "Freelancer Parents Evenings" where successful studio owners discuss financial safety.',
      'Assisting parents in understanding digital design academies and college entry requirements.'
    ],
    description: 'Supporting Wrexham and Valleys guardians to confidently advocate for their children\'s design, media, and artistic career ambitions.',
    contactEmail: 'dylan@creativecarers.org.uk',
    website: 'https://creativecarers.org.uk',
    workingWithOaha: true
  },

  // ==================== STAGE 3: TRANSITIONS (8 organizations) ====================
  {
    id: 'org-newport-bridge-transitions',
    name: 'Newport Tech Bridge',
    location: 'Newport',
    address: 'Kingsway, Newport, NP20 1EX',
    keyContact: 'Dave Jenkins (Industrial Director)',
    currentProjectsCount: 5,
    impact: 'Placed 110 tertiary software students into direct commercial micro-projects.',
    lookingForDetail: 'Software engineers to co-teach short modules.',
    latitude: 51.5880,
    longitude: -2.9978,
    assignedTab: 'Transitions',
    sector: 'Tech/Digital',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Injecting live micro-projects from software companies directly into local FE colleges to replace abstract curriculum tasks.',
    solutions: [
      'Enabling software leaders to co-teach core modules alongside tertiary lecturers.',
      'Running 4-week hybrid transition sprints matching classroom skills with immediate software needs.',
      'Providing students with direct feedback from commercial engineers to build professional portfolios.'
    ],
    description: 'A dedicated alignment vehicle bridging the gap between Newport\'s growing tech sector and local college curriculum designers.',
    contactEmail: 'bridge@newporttech.cymru',
    website: 'https://newporttech.cymru',
    workingWithOaha: true
  },
  {
    id: 'org-wrexham-green-skills-transitions',
    name: 'Wrexham Green Skills Academy',
    location: 'Wrexham',
    address: 'Chester Road, Wrexham, LL11 2SX',
    keyContact: 'Chris Edwards (Senior Tutor)',
    currentProjectsCount: 4,
    impact: 'Certified 85 young construction workers in low-carbon heat pump retrofitting.',
    lookingForDetail: 'Green construction contractors for guaranteed fast-track interviews.',
    latitude: 53.0430,
    longitude: -3.0018,
    assignedTab: 'Transitions',
    sector: 'Green Economy',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Training young builders and engineers in advanced retrofitting and heat-pump technology during their final college year.',
    solutions: [
      'Setting up physical modular testing rigs at Coleg Cambria for practical green technology trial runs.',
      'Structuring guaranteed fast-track interview schemes with green contractors upon graduation.',
      'Creating curriculum components covering Wales\' Net-Zero strategic objectives.'
    ],
    description: 'A pioneering partnership focused on prepping North Wales youth for the immediate demands of low-carbon housing developments.',
    contactEmail: 'hello@wrexhamgreenskills.cymru',
    website: 'https://wrexhamgreenskills.cymru',
    workingWithOaha: true
  },
  {
    id: 'org-gwent-green-energy-transitions',
    name: 'Gwent Green Energy Group',
    location: 'Newport',
    address: 'Cardiff Road, Newport, NP20 2HA',
    keyContact: 'Amanda Lewis (Renewables Coordinator)',
    currentProjectsCount: 3,
    impact: 'Structured offshore wind safety certifications for 70 local school leavers.',
    lookingForDetail: 'Fresh referrals of school leavers from local high schools.',
    latitude: 51.5930,
    longitude: -3.0050,
    assignedTab: 'Transitions',
    sector: 'Green Economy',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Structuring on-site wind and solar maintenance workshops for school leavers in collaboration with energy networks.',
    solutions: [
      'Establishing a modern industrial apprenticeship curriculum focusing on renewables.',
      'Sponsoring travel cards for young rural trainees migrating into town for industrial site placements.',
      'Delivering safety and carbon-literacy certifications for school-leavers.'
    ],
    description: 'An industry-led cooperative bridging the technical education framework with physical offshore and onshore wind operations.',
    contactEmail: 'placement@gwentgreen.org',
    website: 'https://gwentgreen.org',
    workingWithOaha: false
  },
  {
    id: 'org-swansea-green-build-transitions',
    name: 'Swansea Green Build Coalition',
    location: 'Swansea',
    address: 'Kingsway, Swansea, SA1 5JE',
    keyContact: 'Dylan Morris (Green Tech Lead)',
    currentProjectsCount: 4,
    impact: 'Trained 95 learners in eco-building techniques and solar installation basics.',
    lookingForDetail: 'Additional funding for retrofitting simulation tools.',
    latitude: 51.6190,
    longitude: -3.9480,
    assignedTab: 'Transitions',
    sector: 'Green Economy',
    lookingFor: 'Funding',
    capacityStatus: 'Active Cohorts Open',
    currentProject: 'Integrating hands-on eco-building materials and insulation courses directly into standard college bricklaying tracks.',
    solutions: [
      'Providing guest lectures on circular timber framing and hempcrete technology.',
      'Coordinating live community-centre retrofitting days for students to practice.',
      'Facilitating direct pipelines to local green building firms.'
    ],
    description: 'Transforming traditional construction education into future-facing green career pathways in South West Wales.',
    contactEmail: 'dylan@swanseagreenbuild.co.uk',
    website: 'https://swanseagreenbuild.co.uk',
    workingWithOaha: false
  },
  {
    id: 'org-cardiff-creative-path-transitions',
    name: 'Cardiff Creative Pathways',
    location: 'Cardiff',
    address: 'Bute Street, Cardiff, CF10 5AL',
    keyContact: 'Jessica Taylor (Creative Mentor)',
    currentProjectsCount: 5,
    impact: 'Integrated 60 college media students into real television production shadows.',
    lookingForDetail: 'Creative studios willing to share live briefs for classroom practice.',
    latitude: 51.4650,
    longitude: -3.1660,
    assignedTab: 'Transitions',
    sector: 'Creative',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Injecting professional film and graphics projects directly into Cardiff youth groups and college art courses.',
    solutions: [
      'Organising live portfolio-review breakfasts with regional TV commissioners.',
      'Conducting paid 2-week studio simulations to replace standard work experience.',
      'Guiding young creatives in setting up freelancer VAT and billing setups.'
    ],
    description: 'Providing a bridge from media theory to high-value commercial design and television production roles in Wales.',
    contactEmail: 'jess@cardiffcreativepathways.org',
    website: 'https://cardiffcreativepathways.org',
    workingWithOaha: true
  },
  {
    id: 'org-parent-connect-transitions',
    name: 'Cardiff Parent Career Guild',
    location: 'Cardiff',
    address: 'Fitzalan Place, Cardiff, CF24 0EL',
    keyContact: 'Robert Lloyd (Project Director)',
    currentProjectsCount: 4,
    impact: 'Co-created 8 secondary-to-workplace orientation weekends with 120 parent and student participants.',
    lookingForDetail: 'Corporate sponsorship to scale the transition camps to North Wales.',
    latitude: 51.4826,
    longitude: -3.1781,
    assignedTab: 'Transitions',
    sector: 'Creative',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Developing "Parent-Guided Work Placements" allowing parents to visit workspaces alongside transitioning youths.',
    solutions: [
      'Organising dual-invite employer breakfast mornings to establish trust between parents and prospective recruiters.',
      'Translating modern digital workflow jargon into accessible career templates.',
      'Delivering micro-grant schemes supporting transport for initial work shadowing.'
    ],
    description: 'Fostering seamless high school and college exits by actively involving family structures in the initial job-shadowing transitions.',
    contactEmail: 'guild@cardiffparents.org',
    website: 'https://cardiffparents.org',
    workingWithOaha: false
  },
  {
    id: 'org-valley-foundry-transitions',
    name: 'Valleys Foundational Apprentices',
    location: 'Valleys (Pontypridd)',
    address: 'High Street, Pontypridd, CF37 1QT',
    keyContact: 'Llyr Morris (Operations Coordinator)',
    currentProjectsCount: 3,
    impact: 'Over 140 vocational graduates successfully placed in local fabrication and infrastructure apprenticeships.',
    lookingForDetail: 'Referrals from local further education (FE) colleges for struggling graduates.',
    latitude: 51.7500,
    longitude: -3.3800,
    assignedTab: 'Transitions',
    sector: 'Foundational',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Bridging technical diplomas in metalwork, carpentry, and building services with immediate regional repair pipelines.',
    solutions: [
      'Coordinating on-site apprenticeships with housing associations.',
      'Reframing high school career advice from academic targets to practical fabrication trades.',
      'Arranging tool vouchers and travel passes for low-income transitioning learners.'
    ],
    description: 'A vital transitional conduit transforming technical college achievements into long-term infrastructure and fabrication careers.',
    contactEmail: 'llyr@valleyfoundry.co.uk',
    website: 'https://valleyfoundry.co.uk',
    workingWithOaha: true
  },
  {
    id: 'org-north-digital-transitions',
    name: 'North Wales Digital Leap',
    location: 'Bangor',
    address: 'Dean Street, Bangor, LL57 1UR',
    keyContact: 'Eleri Owen (Academic Liaison)',
    currentProjectsCount: 4,
    impact: 'Helped 75 local computing students skip abstract theories and secure commercial digital internships.',
    lookingForDetail: 'Academic institutions seeking industry-validated software challenges.',
    latitude: 53.2250,
    longitude: -4.1200,
    assignedTab: 'Transitions',
    sector: 'Tech/Digital',
    lookingFor: 'Referrals',
    capacityStatus: 'Active Cohorts Open',
    currentProject: 'Replacing legacy high-school ICT modules with real-world web applications and API training courses in Bangor.',
    solutions: [
      'Delivering certified bootcamps that overlap with student\'s final semesters.',
      'Guiding local teachers on the real software skills demanded by northern technology hubs.',
      'Setting up remote workspace simulated tasks that yield immediate student portfolios.'
    ],
    description: 'Dismantling outdated computer curriculums in schools to ensure that learners exit directly with industry-validated digital capabilities.',
    contactEmail: 'eleri@digitalleap.cymru',
    website: 'https://digitalleap.cymru',
    workingWithOaha: false
  },

  // ==================== STAGE 4: NAVIGATION (8 organizations) ====================
  {
    id: 'org-swansea-pathways-navigation',
    name: 'Swansea Pathway Hub',
    location: 'Swansea',
    address: 'Princess Way, Swansea, SA1 3LW',
    keyContact: 'Megan Davies (Lead Pathways Advisor)',
    currentProjectsCount: 5,
    impact: 'Guided 320 non-traditional learners through multi-year navigation plans.',
    lookingForDetail: 'Support referrals for young people returning to employment.',
    latitude: 51.6214,
    longitude: -3.9436,
    assignedTab: 'Navigation',
    sector: 'Foundational',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Providing multi-year personal mentors who navigate learners through stacked micro-credentials, rather than single linear courses.',
    solutions: [
      'Implementing a custom "Navigational Passport" that stores diverse experiences in one verified Welsh profile.',
      'Hosting peer-led support circles for young people returning to work after mental health breaks.',
      'Providing crisis fund grants to cover emergency travel or clothing during non-linear transitions.'
    ],
    description: 'A holistic advice hub built around the belief that modern youth career paths are non-linear, adaptive, and highly personal.',
    contactEmail: 'support@swanseapathways.org.uk',
    website: 'https://swanseapathways.org.uk',
    workingWithOaha: true
  },
  {
    id: 'org-north-career-navigation',
    name: 'North Wales Career Compass',
    location: 'Bangor',
    address: 'Ffordd Deiniol, Bangor, LL57 2UP',
    keyContact: 'Arwyn Hughes (Digital Architect)',
    currentProjectsCount: 3,
    impact: 'Launched an interactive course map used by over 1,500 students across Gwynedd.',
    lookingForDetail: 'Tech companies for neurodivergent virtual peer mentors.',
    latitude: 53.2184,
    longitude: -4.1390,
    assignedTab: 'Navigation',
    sector: 'Tech/Digital',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'An interactive, game-like dashboard mapping vocational courses, volunteering, and small gigs into cohesive career tracks.',
    solutions: [
      'Building a visual map of local training alternatives that do not require GCSE English or Maths to enter.',
      'Offering one-on-one virtual mentoring with neurodivergent industry professionals.',
      'Facilitating direct channels for young freelancers to connect with Welsh micro-studios.'
    ],
    description: 'A developer-led non-profit designing digital visual navigation maps for learners who reject traditional corporate routes.',
    contactEmail: 'compass@careercompass.cymru',
    website: 'https://careercompass.cymru',
    workingWithOaha: false
  },
  {
    id: 'org-mid-stepping-stones-navigation',
    name: 'Mid Wales Stepping Stones',
    location: 'Aberystwyth',
    address: 'Terrace Road, Aberystwyth, SY23 1NY',
    keyContact: 'Elin Evans (Youth Coach)',
    currentProjectsCount: 4,
    impact: 'Assisted 140 rural school leavers in stacking micro-credentials into a viable CV.',
    lookingForDetail: 'Funding for emergency rural travel and training clothing.',
    latitude: 52.4170,
    longitude: -4.0810,
    assignedTab: 'Navigation',
    sector: 'Foundational',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Supporting young people with complex backgrounds to access training across Carmarthenshire and Ceredigion.',
    solutions: [
      'Conducting weekly navigation circles in community libraries.',
      'Providing small bursaries for safety boots, work wear, and local bus passes.',
      'Advocating for learners facing complicated qualification requirements.'
    ],
    description: 'Helping young rural people build secure paths when formal college systems don\'t fit their immediate life challenges.',
    contactEmail: 'elin@steppingstonesmid.cymru',
    website: 'https://steppingstonesmid.cymru',
    workingWithOaha: false
  },
  {
    id: 'org-valleys-navigator-navigation',
    name: 'Valleys Youth Navigator Network',
    location: 'Valleys (Pontypridd)',
    address: 'Taff Street, Pontypridd, CF37 4UA',
    keyContact: 'Rebecca Owen (Pathways Advocate)',
    currentProjectsCount: 4,
    impact: 'Reduced local youth drop-out rates during college-to-work transitions by 22% in Pontypridd.',
    lookingForDetail: 'Referral coordination with local mental health charities.',
    latitude: 51.6020,
    longitude: -3.3420,
    assignedTab: 'Navigation',
    sector: 'Foundational',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Assigning a dedicated transition worker to every young person leaving care, supporting them for up to three years.',
    solutions: [
      'Negotiating flexible start dates and entry adjustments with employers.',
      'Supporting young care-leavers through repeated job and training applications.',
      'Running peer-support circles where young navigators share survival tips.'
    ],
    description: 'Ensuring care leavers and vulnerable youths have deep advocacy and navigational guidance as they enter Welsh workspaces.',
    contactEmail: 'rebecca@valleysnavigator.wales',
    website: 'https://valleysnavigator.wales',
    workingWithOaha: false
  },
  {
    id: 'org-south-vocational-navigation',
    name: 'South Wales Vocational Guide',
    location: 'Port Talbot',
    address: 'Station Road, Port Talbot, SA13 1DE',
    keyContact: 'Thomas Rees (Vocational Mentor)',
    currentProjectsCount: 3,
    impact: 'Created a streamlined portfolio system adopted by 12 local training providers.',
    lookingForDetail: 'Employers to join informal creative review circles instead of resumes.',
    latitude: 51.5940,
    longitude: -3.7840,
    assignedTab: 'Navigation',
    sector: 'Creative',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Helping vocational graduates compile non-traditional portfolios that highlight practical trades over academic marks.',
    solutions: [
      'Creating digital portfolios demonstrating hands-on metalwork, carpentry, or digital designs.',
      'Mentoring graduates through the interview processes of major industrial contractors.',
      'Publishing case studies illustrating the business success of non-academic hires.'
    ],
    description: 'Reforming how vocational skills are valued, ensuring local talent is judged on capability and physical projects.',
    contactEmail: 'tom@southvocational.org.uk',
    website: 'https://southvocational.org.uk',
    workingWithOaha: true
  },
  {
    id: 'org-cyo-navigation',
    name: 'Cymru Youth Outreach (CYO)',
    location: 'Valleys (Merthyr Tydfil)',
    address: '12 High Street, Merthyr Tydfil, CF47 8DP',
    keyContact: 'Gareth Jenkins (Director of Engagement)',
    currentProjectsCount: 4,
    impact: 'Successfully co-navigated 85 long-term unemployed youth back into continuous apprenticeships.',
    lookingForDetail: 'Employers willing to accept candidate trials without complex academic screening.',
    latitude: 51.7481,
    longitude: -3.3796,
    assignedTab: 'Navigation',
    sector: 'Foundational',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Coaching youths with criminal records or gaps in education to map non-traditional, direct work entry-points.',
    solutions: [
      'Advocating for employers to drop standard background filters for entry roles.',
      'Providing a designated youth mentor during the initial three critical months of employment.',
      'Helping youths negotiate non-traditional training and transport barriers.'
    ],
    description: 'CYO is dedicated to reaching young people aged 16-24 who have disengaged from formal education and statutory job centres in the South Wales Valleys.',
    contactEmail: 'contact@cyo.wales',
    website: 'https://cyo.wales',
    workingWithOaha: true
  },
  {
    id: 'org-clwyd-green-navigation',
    name: 'Clwyd Green Navigation Group',
    location: 'Wrexham',
    address: 'Pen-Y-Bryn, Wrexham, LL13 7HY',
    keyContact: 'Heulwen Morris (Eco Advisor)',
    currentProjectsCount: 3,
    impact: 'Plotted cohesive multi-stage environmental careers for 60 local farm hands.',
    lookingForDetail: 'Direct referrals from local rural and farming unions.',
    latitude: 53.0490,
    longitude: -2.9960,
    assignedTab: 'Navigation',
    sector: 'Green Economy',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Charting personalized paths through environmental audits, carbon capture, forestry, and sustainable water logistics.',
    solutions: [
      'Breaking down complex carbon consulting standards into sequential, stackable certificates.',
      'Offering transport assistance from remote smallholdings to training forests.',
      'Guiding young eco-activists to combine volunteering into formal job applications.'
    ],
    description: 'Providing crucial navigational coordinates for young rural North-East Wales workers eager to shape low-carbon land pathways.',
    contactEmail: 'heulwen@clwydgreennav.co.uk',
    website: 'https://clwydgreennav.co.uk',
    workingWithOaha: true
  },
  {
    id: 'org-coastal-creative-navigation',
    name: 'Coastal Creative Route',
    location: 'Aberystwyth',
    address: 'Bridge Street, Aberystwyth, SY23 1QA',
    keyContact: 'Rhodri Davies (Creative Coach)',
    currentProjectsCount: 3,
    impact: 'Secured funding and training support for 45 rural digital creators.',
    lookingForDetail: 'Sponsors seeking to fund rural digital scholarships and hardware packs.',
    latitude: 52.4150,
    longitude: -4.0860,
    assignedTab: 'Navigation',
    sector: 'Creative',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Empowering young isolated artists, musicians and filmmakers to build remote freelance careers in Mid Wales.',
    solutions: [
      'Hosting rural virtual network boards connecting mentors and learners.',
      'Delivering specific guides on managing remote client projects and contracts.',
      'Providing hardware loan grants to support initial digital work.'
    ],
    description: 'Navigating rural creatives around traditional urban-centric agency bias, building viable micro-businesses in West Wales.',
    contactEmail: 'rhodri@coastalcreativeroute.cymru',
    website: 'https://coastalcreativeroute.cymru',
    workingWithOaha: false
  },

  // ==================== STAGE 5: TRANSLATION (8 organizations) ====================
  {
    id: 'org-cymru-green-careers-translation',
    name: 'Cymru Green Careers',
    location: 'Swansea',
    address: 'Wind Street, Swansea, SA1 1DY',
    keyContact: 'Alun Davies (Technical Translator)',
    currentProjectsCount: 3,
    impact: 'Replaced complex net-zero jargon with "Green Career Dictionaries" for 40 secondary schools.',
    lookingForDetail: 'Climate-focused companies to co-design simple role descriptions.',
    latitude: 51.6264,
    longitude: -3.9350,
    assignedTab: 'Translation',
    sector: 'Green Economy',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Translating net-zero terminology into everyday language, matching high-demand circular economy jobs with youth passions.',
    solutions: [
      'Publishing a "Green Career Dictionary" that matches skills like "fixing bikes" to "circular logistics".',
      'Running simulation workshops where youth try out environmental auditing in local parks.',
      'Creating employer training modules on how to write inclusive job specifications without excessive industry jargon.'
    ],
    description: 'A translation catalyst bridging the green corporate sector with Welsh secondary education networks.',
    contactEmail: 'translate@greencareers.cymru',
    website: 'https://greencareers.cymru',
    workingWithOaha: true
  },
  {
    id: 'org-cardiff-creative-translation',
    name: 'Cardiff Creative Guild',
    location: 'Cardiff',
    address: 'Westgate Street, Cardiff, CF10 1DP',
    keyContact: 'Lowri Price (Guild Director)',
    currentProjectsCount: 4,
    impact: 'Translated 30 media studio briefs into youth-friendly challenges, leading to 18 hires.',
    lookingForDetail: 'Media and gaming studios looking for fresh entry-level designers.',
    latitude: 51.4760,
    longitude: -3.1850,
    assignedTab: 'Translation',
    sector: 'Creative',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Translating media studio briefs into community design challenges, giving local youths direct experience and credit before applying.',
    solutions: [
      'Replacing formal resume requirements with collaborative, informal creative review circles.',
      'Translating corporate marketing terminology into practical design skills classes.',
      'Fostering direct dialogue sessions between media executives and young Welsh-language creators.'
    ],
    description: 'A dynamic guild of musicians, designers, and film producers demystifying creative jargon for Cardiff\'s diverse youth.',
    contactEmail: 'hello@cardiffcreativeguild.co.uk',
    website: 'https://cardiffcreativeguild.co.uk',
    workingWithOaha: false
  },
  {
    id: 'org-wrexham-tech-trans-translation',
    name: 'Wrexham Tech Translator',
    location: 'Wrexham',
    address: 'Henblas Street, Wrexham, LL13 8AE',
    keyContact: 'Jac Roberts (Digital Coach)',
    currentProjectsCount: 3,
    impact: 'Translated "React development" and "data analysis" jargon into local school workshop guides.',
    lookingForDetail: 'Software firms wanting to write inclusive role requirements.',
    latitude: 53.0450,
    longitude: -3.0040,
    assignedTab: 'Translation',
    sector: 'Tech/Digital',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Breaking down technical descriptions into straightforward core tasks for school-leavers.',
    solutions: [
      'Converting abstract job criteria into specific projects (e.g. "building forms").',
      'Publishing bite-sized newsletters for school teachers listing actual tech skills needed.',
      'Advising regional businesses on replacing five-stage technical tests with half-day trial sessions.'
    ],
    description: 'Bridging technical definitions and local school realities, turning corporate requirements into achievable career tasks.',
    contactEmail: 'jac@wrexhamtechtranslator.cymru',
    website: 'https://wrexhamtechtranslator.cymru',
    workingWithOaha: false
  },
  {
    id: 'org-gwent-language-translation',
    name: 'Gwent Language & Work Hub',
    location: 'Newport',
    address: 'High Street, Newport, NP20 1GF',
    keyContact: 'Kelly Evans (Communications Officer)',
    currentProjectsCount: 3,
    impact: 'Conducted 15 jargon-busting workshops attended by 300+ Newport school leavers.',
    lookingForDetail: 'Funding to expand bilingual work glossary publications.',
    latitude: 51.5890,
    longitude: -2.9920,
    assignedTab: 'Translation',
    sector: 'Foundational',
    lookingFor: 'Funding',
    capacityStatus: 'Active Cohorts Open',
    currentProject: 'Converting corporate HR speak into plain English and Welsh for apprenticeship candidates.',
    solutions: [
      'Creating custom jargon-free application assistance templates.',
      'Publishing a bilingual glossary of vocational and industrial jargon.',
      'Running mock interview days where corporate leaders practice speaking plainly.'
    ],
    description: 'Demystifying the language barrier in HR and employment, ensuring young, capable people aren\'t filtered out by elite wording.',
    contactEmail: 'kelly@gwentworkhub.org',
    website: 'https://gwentworkhub.org',
    workingWithOaha: true
  },
  {
    id: 'org-llanelli-circular-translation',
    name: 'Llanelli Circular Translation',
    location: 'Llanelli',
    address: 'Murray Street, Llanelli, SA15 1AQ',
    keyContact: 'Rhys Thomas (Circular Lead)',
    currentProjectsCount: 3,
    impact: 'Replaced formal interview scripts with "passion discovery days" for 8 circular employers.',
    lookingForDetail: 'Local retail and waste recycling partners.',
    latitude: 51.6840,
    longitude: -4.1560,
    assignedTab: 'Translation',
    sector: 'Green Economy',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Connecting recycling, upcycling, and circular economy operations with enthusiastic young builders.',
    solutions: [
      'Reframing technical terms like "waste audit" into practical actions like "resource sorting".',
      'Running community repair sessions where young mechanics practice on domestic goods.',
      'Coaching small green circular businesses on creating welcoming youth placements.'
    ],
    description: 'Helping environmental businesses frame jobs around action, curiosity, and practical repairing skills.',
    contactEmail: 'rhys@circularllanelli.cymru',
    website: 'https://circularllanelli.cymru',
    workingWithOaha: true
  },
  {
    id: 'org-cyo-translation',
    name: 'Cymru Youth Outreach (CYO)',
    location: 'Valleys (Merthyr Tydfil)',
    address: '12 High Street, Merthyr Tydfil, CF47 8DP',
    keyContact: 'Gareth Jenkins (Director of Engagement)',
    currentProjectsCount: 4,
    impact: 'Rewrote 42 industrial role outlines for South Wales trade networks to use plain-text phrasing.',
    lookingForDetail: 'Youth referrals from family hubs and community support structures.',
    latitude: 51.7461,
    longitude: -3.3776,
    assignedTab: 'Translation',
    sector: 'Foundational',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Translating statutory employment framework forms and job centre documents into young-friendly visual guides.',
    solutions: [
      'Converting complex job application jargon into simple mobile chat dialogues.',
      'Conducting focus groups helping businesses swap HR wording with plain English.',
      'Designing video applications to replace written CV structures for local NEET youths.'
    ],
    description: 'CYO is dedicated to reaching young people aged 16-24 who have disengaged from formal education and statutory job centres in the South Wales Valleys.',
    contactEmail: 'contact@cyo.wales',
    website: 'https://cyo.wales',
    workingWithOaha: true
  },
  {
    id: 'org-wrexham-green-skills-translation',
    name: 'Wrexham Green Skills Academy',
    location: 'Wrexham',
    address: 'Chester Road, Wrexham, LL11 2SX',
    keyContact: 'Chris Edwards (Senior Tutor)',
    currentProjectsCount: 4,
    impact: 'Helped 130 local candidates decode retrofitting certifications to access green jobs.',
    lookingForDetail: 'Unemployed youth referrals looking for sustainable energy careers.',
    latitude: 53.0440,
    longitude: -3.0028,
    assignedTab: 'Translation',
    sector: 'Green Economy',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Translating global climate directives and carbon standards into understandable, on-site construction tasks.',
    solutions: [
      'Explaining "Net Zero pathways" via straightforward hands-on insulation workshops.',
      'Replacing dense thermal calculations with visual heat maps for learners.',
      'Structuring simple Welsh-language toolkits matching traditional building skills to green retrofits.'
    ],
    description: 'A pioneering partnership focused on prepping North Wales youth for the immediate demands of low-carbon housing developments.',
    contactEmail: 'hello@wrexhamgreenskills.cymru',
    website: 'https://wrexhamgreenskills.cymru',
    workingWithOaha: true
  },
  {
    id: 'org-bangor-translation-translation',
    name: 'Bangor Bilingual Tech Guild',
    location: 'Bangor',
    address: 'Garth Road, Bangor, LL57 2RP',
    keyContact: 'Gwenllian Evans (Communications Lead)',
    currentProjectsCount: 3,
    impact: 'Mapped and translated 25 software roles into Welsh-language student career maps.',
    lookingForDetail: 'Tech funding bodies to support translation glossary publications.',
    latitude: 53.2264,
    longitude: -4.1283,
    assignedTab: 'Translation',
    sector: 'Tech/Digital',
    lookingFor: 'Funding',
    capacityStatus: 'Active Cohorts Open',
    currentProject: 'Ensuring tech terminologies are translated bilingually, creating local Welsh-language software apprenticeships.',
    solutions: [
      'Coordinating Welsh-English tech glossary maps for northern schools.',
      'Encouraging software startups to write accessible dual-language job details.',
      'Delivering interactive workshops connecting Welsh-speakers to global coding frameworks.'
    ],
    description: 'An academic and industry collaborative translating advanced coding jargon into accessible Welsh-language student pipelines.',
    contactEmail: 'gwenllian@bangortechguild.cymru',
    website: 'https://bangortechguild.cymru',
    workingWithOaha: false
  },

  // ==================== STAGE 6: PROGRESSION (8 organizations) ====================
  {
    id: 'org-inclusive-workplaces-progression',
    name: 'Inclusive Workplaces Wales',
    location: 'Newport',
    address: 'Cardiff Road, Newport, NP20 2BP',
    keyContact: 'Dr. Helen Price (Culture Consultant)',
    currentProjectsCount: 4,
    impact: 'Audited 18 Welsh tech firms, establishing transparent youth progression systems for 120 employees.',
    lookingForDetail: 'Funding from larger corporations to sponsor cross-company buddy systems.',
    latitude: 51.5830,
    longitude: -2.9900,
    assignedTab: 'Progression',
    sector: 'Tech/Digital',
    lookingFor: 'Funding',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Coaching major Welsh tech firms to replace toxic "hustle culture" with structured youth progression pathways and transparent reviews.',
    solutions: [
      'Establishing cross-company anonymous buddy systems for new hires under 25.',
      'Running workplace culture audits to spot invisible barriers to progression (e.g. transport limits).',
      'Coaching youth hires on advocating for raises, training budgets, and mental health support.'
    ],
    description: 'An advocacy collective and consulting trust addressing high drop-out rates of young apprentices due to non-inclusive workplace cultures.',
    contactEmail: 'progression@inclusiveworkplaces.cymru',
    website: 'https://inclusiveworkplaces.cymru',
    workingWithOaha: true
  },
  {
    id: 'org-wrexham-apprentice-progression',
    name: 'Wrexham Apprentice Alliance',
    location: 'Wrexham',
    address: 'Industrial Estate, Wrexham, LL13 9UF',
    keyContact: 'Ian Jones (Alliance Chairman)',
    currentProjectsCount: 3,
    impact: 'Trained 45 manufacturing site managers in empathetic coaching, boosting apprentice retention by 35%.',
    lookingForDetail: 'Additional industrial employers to join our active forums.',
    latitude: 53.0380,
    longitude: -3.0100,
    assignedTab: 'Progression',
    sector: 'Foundational',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Setting up local "Apprentice Forums" where young industrial tradespeople peer-review workplace conditions and safety.',
    solutions: [
      'Delivering confidence workshops for young hires in traditional manufacturing and logistics environments.',
      'Training experienced industrial site managers in contemporary empathetic mentoring techniques.',
      'Conducting focus groups on youth retention to feed back directly to Welsh industry leaders.'
    ],
    description: 'An active trade alliance establishing fair progression, safe workspaces, and positive retention strategies in Welsh manufacturing.',
    contactEmail: 'alliance@wrexhamapprentices.co.uk',
    website: 'https://wrexhamapprentices.co.uk',
    workingWithOaha: false
  },
  {
    id: 'org-cardiff-safe-harbours-progression',
    name: 'Cardiff Safe Harbours',
    location: 'Cardiff',
    address: 'Cathedral Road, Cardiff, CF11 9HA',
    keyContact: 'Sian Griffiths (Inclusion Coach)',
    currentProjectsCount: 4,
    impact: 'Established peer support communities for 80 young minority hires in retail and hospitality.',
    lookingForDetail: 'Employer partners wanting to run workplace culture audits.',
    latitude: 51.4880,
    longitude: -3.1920,
    assignedTab: 'Progression',
    sector: 'Foundational',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Active Cohorts Open',
    currentProject: 'Running support networks and advice sessions for young hires from minority and under-represented background in Welsh service sectors.',
    solutions: [
      'Conducting evening support and legal advice drop-ins.',
      'Sponsoring peer mentoring programs matching young hires with experienced industry figures.',
      'Working with managers to create reporting systems for workplace prejudice.'
    ],
    description: 'Supporting diverse young talent to survive and thrive in traditional service, retail, and hospitality careers across South Wales.',
    contactEmail: 'sian@cardiffsafeharbours.org.uk',
    website: 'https://cardiffsafeharbours.org.uk',
    workingWithOaha: true
  },
  {
    id: 'org-swansea-advocacy-progression',
    name: 'Swansea Youth Advocacy Council',
    location: 'Swansea',
    address: 'Walter Road, Swansea, SA1 5NN',
    keyContact: 'Darren Williams (Advocacy Director)',
    currentProjectsCount: 3,
    impact: 'Guided 60 young apprentices through safe channels to negotiate contract terms and training hours.',
    lookingForDetail: 'Employer partners committed to transparent, fair-wage salary scales.',
    latitude: 51.6160,
    longitude: -3.9580,
    assignedTab: 'Progression',
    sector: 'Creative',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Assisting young professionals in creative industries with salary and workplace safety negotiations.',
    solutions: [
      'Establishing a modern advisory board covering creative freelancer rights.',
      'Holding workshops on identifying unfair workplace demands or unpaid overtime.',
      'Sponsoring youth-friendly legal documents and contract templates.'
    ],
    description: 'A dedicated guild giving young creators and trainees the direct advocacy needed to advance in media, design, and software.',
    contactEmail: 'darren@swanseaadvocacy.org',
    website: 'https://swanseaadvocacy.org',
    workingWithOaha: false
  },
  {
    id: 'org-valleys-progression-progression',
    name: 'Valleys Progression Pathways',
    location: 'Valleys (Aberdare)',
    address: 'Canon Street, Aberdare, CF44 7AP',
    keyContact: 'Lisa Owen (Retention Specialist)',
    currentProjectsCount: 4,
    impact: 'Worked with 12 local logistics firms to secure transport and flexible shift hours for young rural hires.',
    lookingForDetail: 'Logistics and construction employers in Cynon Valley.',
    latitude: 51.7140,
    longitude: -3.4450,
    assignedTab: 'Progression',
    sector: 'Foundational',
    lookingFor: 'Employer Partners',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Ensuring young workers in traditional manufacturing, logistics and driving hubs have fair progression schedules.',
    solutions: [
      'Creating structured training calendars mapped to regular progression rewards.',
      'Delivering confidence sessions for young workers transitioning into team leader roles.',
      'Developing transport-matching schemes for rural night-shift logistics workers.'
    ],
    description: 'Protecting and growing talent in traditional valleys industries, turning high-turnover entry jobs into permanent careers.',
    contactEmail: 'lisa@valleysprogression.wales',
    website: 'https://valleysprogression.wales',
    workingWithOaha: false
  },
  {
    id: 'org-wrexham-green-skills-progression',
    name: 'Wrexham Green Skills Academy',
    location: 'Wrexham',
    address: 'Chester Road, Wrexham, LL11 2SX',
    keyContact: 'Chris Edwards (Senior Tutor)',
    currentProjectsCount: 4,
    impact: 'Monitored retention rates for 55 green construction graduates across North Wales.',
    lookingForDetail: 'Referrals from local councils or green builders looking to verify apprentice safety.',
    latitude: 53.0420,
    longitude: -3.0008,
    assignedTab: 'Progression',
    sector: 'Green Economy',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Advocating for long-term health, safety and professional development of young heat-pump retrofitting crews.',
    solutions: [
      'Running workplace inclusion audits for commercial low-carbon plumbing firms.',
      'Fostering peer retention boards to discuss green industrial work conditions.',
      'Coaching young engineering crews in contract advocacy and safe work hours.'
    ],
    description: 'A pioneering partnership focused on prepping North Wales youth for the immediate demands of low-carbon housing developments.',
    contactEmail: 'hello@wrexhamgreenskills.cymru',
    website: 'https://wrexhamgreenskills.cymru',
    workingWithOaha: true
  },
  {
    id: 'org-west-green-progression',
    name: 'West Wales Green Builders',
    location: 'Llanelli',
    address: 'Vaughan Street, Llanelli, SA15 3TY',
    keyContact: 'Ceri James (Retention Coach)',
    currentProjectsCount: 3,
    impact: 'Established multi-year promotion schemes with 6 major Carmarthenshire green developments.',
    lookingForDetail: 'Funding to expand training vouchers and mental health mentors.',
    latitude: 51.6822,
    longitude: -4.1620,
    assignedTab: 'Progression',
    sector: 'Green Economy',
    lookingFor: 'Funding',
    capacityStatus: 'Seeking Partners',
    currentProject: 'Ensuring young retrofitting and solar installation apprentices have transparent pathways to project leader roles.',
    solutions: [
      'Developing transparent wage structures based on practical certified tasks.',
      'Offering emotional support coaching sessions for young people working in harsh outdoor sites.',
      'Fostering mutual collaboration networks among green tradespeople.'
    ],
    description: 'A dedicated trust guaranteeing fair wages, safe conditions, and permanent progression pipelines for West Wales green recruits.',
    contactEmail: 'ceri@westgreenbuilders.cymru',
    website: 'https://westgreenbuilders.cymru',
    workingWithOaha: true
  },
  {
    id: 'org-gwent-tech-progression',
    name: 'Gwent Youth Tech Advocates',
    location: 'Newport',
    address: 'Bridge Street, Newport, NP20 4AN',
    keyContact: 'Meirion Davies (Inclusion Analyst)',
    currentProjectsCount: 3,
    impact: 'Audited 10 digital agencies, securing career advancement reviews for 45 junior developers.',
    lookingForDetail: 'Referrals of junior programmers seeking workplace contract advice.',
    latitude: 51.5925,
    longitude: -3.0020,
    assignedTab: 'Progression',
    sector: 'Tech/Digital',
    lookingFor: 'Referrals',
    capacityStatus: 'Accepting Referrals',
    currentProject: 'Protecting junior software engineers from excessive hours and establishing clear quarterly progression targets.',
    solutions: [
      'Reviewing entry-level developer salaries to match rising digital industry standards.',
      'Delivering confidence coaching on contract negotiation and performance reviews.',
      'Partnering with HR managers to replace outdated hierarchies with merit-based software targets.'
    ],
    description: 'An independent advisory council championing fair progression, psychological safety, and clear promotion milestones for Newport\'s junior developers.',
    contactEmail: 'meirion@gwenttechadvocates.org',
    website: 'https://gwenttechadvocates.org',
    workingWithOaha: false
  }
];
